#####################################################################
## file        : test makefile for build current dir .c            ##
## author      : liujifeng                                         ##
## date-time   : 12/14/2019                                        ##
## 原文链接：https://blog.csdn.net/jenie/article/details/106893512
#####################################################################

# 此功能是编译当前所有文件的c或者cpp的文件
CC = gcc
CPP = g++
RM = rm -rf
